/**
 * Audit Report PDF Generator
 *
 * Generates structured audit reports for EUDR, organic, social compliance,
 * GACC, and general audit types. Follows the certificate-pdf.ts pattern
 * using jsPDF + jsPDF-autotable.
 *
 * Returns a base64 data URI string.
 */

export type AuditReportType = 'eudr' | 'organic' | 'social_compliance' | 'gacc' | 'general';

export interface FarmRecord {
  id: string;
  farmer_name: string;
  community: string;
  state: string;
  boundary_geo: boolean;
  deforestation_check: string | null;
  consent_timestamp: string | null;
  compliance_status: string;
}

export interface BatchRecord {
  id: string;
  batch_code: string;
  total_weight: number;
  bag_count: number;
  collection_date: string;
  farmer_name?: string;
}

export interface LabResultRecord {
  id: string;
  lab_provider: string;
  test_type: string;
  test_date: string;
  result: string;
  certificate_number?: string;
  certificate_expiry_date?: string;
}

export interface ShipmentRecord {
  id: string;
  shipment_code?: string;
  destination_country: string;
  status: string;
  total_weight_kg?: number;
  created_at: string;
}

export interface DdsRecord {
  id: string;
  shipment_id: string;
  prenotif_eu_traces: string;
  prenotif_eu_traces_ref?: string;
}

export interface PaymentRecord {
  id: string;
  payee_name: string;
  amount: number;
  currency: string;
  payment_date: string;
  status: string;
}

export interface AuditReportData {
  reportType: AuditReportType;
  orgName: string;
  period: { from: string; to: string };
  farms: FarmRecord[];
  batches: BatchRecord[];
  labResults: LabResultRecord[];
  shipments: ShipmentRecord[];
  ddsSubmissions: DdsRecord[];
  payments?: PaymentRecord[];
  generatedBy: string;
  generatedAt: string;
  auditReadiness?: {
    overall: number;
    grade: string;
  };
}

const REPORT_TITLES: Record<AuditReportType, string> = {
  eudr:             'EUDR Compliance Audit Report',
  organic:          'Organic Certification Audit Report',
  social_compliance:'Social Compliance Audit Report',
  gacc:             'GACC Registration Audit Report',
  general:          'General Compliance Audit Report',
};

const HEADER_COLOR: [number, number, number] = [22, 101, 52]; // green-800
const ACCENT_COLOR: [number, number, number] = [240, 253, 244]; // green-50
const TEXT_DARK:    [number, number, number] = [17, 24, 39];
const TEXT_MID:     [number, number, number] = [75, 85, 99];
const BORDER_COLOR: [number, number, number] = [209, 213, 219];

export async function generateAuditReportPdf(data: AuditReportData): Promise<string> {
  const { jsPDF } = await import('jspdf');
  // @ts-ignore
  await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = 210;
  const margin = 18;
  const contentW = pageW - margin * 2;

  // ─── Cover Page ────────────────────────────────────────────────────────────

  // Header bar
  doc.setFillColor(...HEADER_COLOR);
  doc.rect(0, 0, pageW, 50, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('OriginTrace — Compliance Intelligence Platform', margin, 14);

  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(REPORT_TITLES[data.reportType], margin, 26);

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(data.orgName, margin, 35);
  doc.text(
    `Reporting Period: ${data.period.from} – ${data.period.to}`,
    margin,
    42
  );

  // Audit grade badge (if available)
  if (data.auditReadiness) {
    const badgeX = pageW - margin - 28;
    const gradeColor = gradeToColor(data.auditReadiness.grade);
    doc.setFillColor(...gradeColor);
    doc.roundedRect(badgeX, 8, 26, 26, 3, 3, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(data.auditReadiness.grade, badgeX + 13, 24, { align: 'center' });
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(`${data.auditReadiness.overall}/100`, badgeX + 13, 30, { align: 'center' });
  }

  // Meta box
  let y = 60;
  doc.setFillColor(...ACCENT_COLOR);
  doc.rect(margin, y, contentW, 28, 'F');
  doc.setDrawColor(...BORDER_COLOR);
  doc.rect(margin, y, contentW, 28, 'S');

  doc.setTextColor(...TEXT_DARK);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text('Report Details', margin + 4, y + 7);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_MID);
  doc.text([
    `Report Type:  ${REPORT_TITLES[data.reportType]}`,
    `Generated By: ${data.generatedBy}`,
    `Generated At: ${new Date(data.generatedAt).toLocaleString('en-GB', { timeZone: 'UTC' })} UTC`,
    `Organisation: ${data.orgName}`,
  ], margin + 4, y + 14);

  // Summary statistics row
  y += 38;
  const stats = [
    { label: 'Farms',     value: data.farms.length },
    { label: 'Batches',   value: data.batches.length },
    { label: 'Lab Tests', value: data.labResults.length },
    { label: 'Shipments', value: data.shipments.length },
  ];
  const colW = contentW / stats.length;
  stats.forEach((s, i) => {
    const x = margin + i * colW;
    doc.setFillColor(249, 250, 251);
    doc.rect(x, y, colW - 2, 20, 'F');
    doc.setDrawColor(...BORDER_COLOR);
    doc.rect(x, y, colW - 2, 20, 'S');
    doc.setTextColor(...HEADER_COLOR);
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(String(s.value), x + colW / 2 - 1, y + 12, { align: 'center' });
    doc.setTextColor(...TEXT_MID);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(s.label, x + colW / 2 - 1, y + 18, { align: 'center' });
  });

  // ─── Page 2+: Sections ────────────────────────────────────────────────────

  doc.addPage();

  // Section: Farms
  y = addSectionHeader(doc, '1. Farm Records', margin, 20);
  if (data.farms.length === 0) {
    y = addEmptyNote(doc, 'No farms registered in the reporting period.', margin, y);
  } else {
    // @ts-ignore
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Farmer', 'Community', 'State', 'Boundary', 'Deforestation', 'Consent', 'Status']],
      body: data.farms.map((f) => [
        f.farmer_name,
        f.community,
        f.state,
        f.boundary_geo ? '✓' : '✗',
        f.deforestation_check
          ? (JSON.parse(typeof f.deforestation_check === 'string' ? f.deforestation_check : '{}') as any).risk_level ?? 'checked'
          : 'not checked',
        f.consent_timestamp ? new Date(f.consent_timestamp).toLocaleDateString('en-GB') : '✗',
        capitalize(f.compliance_status),
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontSize: 7, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [249, 250, 251] },
    });
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 8;
  }

  // Section: Batches
  y = addSectionHeader(doc, '2. Collection Batch Records', margin, y);
  if (data.batches.length === 0) {
    y = addEmptyNote(doc, 'No batches in the reporting period.', margin, y);
  } else {
    // @ts-ignore
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Batch Code', 'Collection Date', 'Farmer', 'Weight (kg)', 'Bags']],
      body: data.batches.map((b) => [
        b.batch_code,
        b.collection_date,
        b.farmer_name ?? '—',
        b.total_weight.toLocaleString(),
        b.bag_count,
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontSize: 7, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [249, 250, 251] },
    });
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 8;
  }

  // Section: Lab Results
  if (y > 220) { doc.addPage(); y = 20; }
  y = addSectionHeader(doc, '3. Laboratory Test Results', margin, y);
  if (data.labResults.length === 0) {
    y = addEmptyNote(doc, 'No lab results on file for the reporting period.', margin, y);
  } else {
    // @ts-ignore
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Lab Provider', 'Test Type', 'Test Date', 'Result', 'Certificate No.', 'Expiry']],
      body: data.labResults.map((r) => [
        r.lab_provider,
        r.test_type.replace('_', ' '),
        r.test_date,
        capitalize(r.result),
        r.certificate_number ?? '—',
        r.certificate_expiry_date ?? '—',
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontSize: 7, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [249, 250, 251] },
      didParseCell: (data: any) => {
        if (data.section === 'body' && data.column.index === 3) {
          const val = data.cell.raw as string;
          if (val === 'Fail') data.cell.styles.textColor = [220, 38, 38];
          if (val === 'Pass') data.cell.styles.textColor = [22, 101, 52];
          if (val === 'Conditional') data.cell.styles.textColor = [180, 83, 9];
        }
      },
    });
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 8;
  }

  // Section: Shipments
  if (y > 220) { doc.addPage(); y = 20; }
  y = addSectionHeader(doc, '4. Shipment Records', margin, y);
  if (data.shipments.length === 0) {
    y = addEmptyNote(doc, 'No shipments in the reporting period.', margin, y);
  } else {
    // @ts-ignore
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Shipment Code', 'Destination', 'Status', 'Weight (kg)', 'Created']],
      body: data.shipments.map((s) => [
        s.shipment_code ?? s.id.slice(0, 8),
        s.destination_country,
        capitalize(s.status.replace('_', ' ')),
        s.total_weight_kg?.toLocaleString() ?? '—',
        new Date(s.created_at).toLocaleDateString('en-GB'),
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontSize: 7, fontStyle: 'bold' },
      alternateRowStyles: { fillColor: [249, 250, 251] },
    });
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 8;
  }

  // Section: DDS Submissions (EUDR report type)
  if (data.reportType === 'eudr' && data.ddsSubmissions.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSectionHeader(doc, '5. EU TRACES DDS Submissions', margin, y);
    // @ts-ignore
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Shipment ID', 'TRACES Status', 'Reference Number']],
      body: data.ddsSubmissions.map((d) => [
        d.shipment_id.slice(0, 8),
        capitalize(d.prenotif_eu_traces.replace('_', ' ')),
        d.prenotif_eu_traces_ref ?? '—',
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontSize: 7, fontStyle: 'bold' },
    });
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 8;
  }

  // Section: Payments (social compliance report type)
  if (data.reportType === 'social_compliance' && data.payments && data.payments.length > 0) {
    if (y > 220) { doc.addPage(); y = 20; }
    y = addSectionHeader(doc, '5. Farmer Payment Records', margin, y);
    // @ts-ignore
    doc.autoTable({
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Payee', 'Amount', 'Currency', 'Date', 'Status']],
      body: data.payments.map((p) => [
        p.payee_name,
        p.amount.toLocaleString(),
        p.currency,
        p.payment_date,
        capitalize(p.status),
      ]),
      styles: { fontSize: 7, cellPadding: 2 },
      headStyles: { fillColor: HEADER_COLOR, textColor: 255, fontSize: 7, fontStyle: 'bold' },
    });
    // @ts-ignore
    y = doc.lastAutoTable.finalY + 8;
  }

  // ─── Declaration page ──────────────────────────────────────────────────────
  doc.addPage();
  y = 20;
  y = addSectionHeader(doc, 'Declaration', margin, y);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...TEXT_DARK);

  const declarationText = [
    `This report has been automatically generated by the OriginTrace platform on behalf of ${data.orgName}.`,
    '',
    'The data contained herein is sourced directly from the OriginTrace farm and supply chain management system.',
    'All farm records, batch data, laboratory test results, and shipment records have been submitted by',
    'authorised personnel of the organisation named above.',
    '',
    `Report generated: ${new Date(data.generatedAt).toLocaleString('en-GB', { timeZone: 'UTC' })} UTC`,
    `Generated by: ${data.generatedBy}`,
    '',
    'This document is digitally generated and does not require a wet signature for regulatory submissions.',
    'For verification, contact the issuing organisation directly.',
  ];
  doc.text(declarationText, margin, y + 8);

  // Footer on all pages
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setTextColor(...TEXT_MID);
    doc.text(
      `${data.orgName} — ${REPORT_TITLES[data.reportType]} — Page ${i} of ${totalPages}`,
      pageW / 2,
      293,
      { align: 'center' }
    );
    doc.text('Generated by OriginTrace | origintrace.io', margin, 293);
    doc.text(data.generatedAt.slice(0, 10), pageW - margin, 293, { align: 'right' });
  }

  return doc.output('datauristring');
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function addSectionHeader(doc: any, title: string, x: number, y: number): number {
  doc.setFillColor(...HEADER_COLOR);
  doc.rect(x, y, 210 - x * 2, 7, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'bold');
  doc.text(title, x + 3, y + 5);
  return y + 12;
}

function addEmptyNote(doc: any, msg: string, x: number, y: number): number {
  doc.setTextColor(107, 114, 128);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'italic');
  doc.text(msg, x, y);
  return y + 8;
}

function capitalize(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function gradeToColor(grade: string): [number, number, number] {
  switch (grade) {
    case 'A': return [22, 101, 52];
    case 'B': return [37, 99, 235];
    case 'C': return [180, 83, 9];
    case 'D': return [220, 38, 38];
    default:  return [75, 85, 99];
  }
}
